FROM python:3.11-slim
RUN apt-get update && apt-get install -y libyaml-dev gcc && \
    pip install kafka-python==2.0.2 kubernetes  langgraph langchain-ollama pyyaml requests && \
    apt-get purge -y gcc && apt-get autoremove -y && rm -rf /var/lib/apt/lists/*

ENV OLLAMA_HOST="http://ollama.kitchen-sre.svc.cluster.local:11434"
WORKDIR /app
COPY agents/*.py ./
CMD ["python", "control_plane.py"]

