apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
  namespace: kitchen-sre
spec:
  type: NodePort
  ports:
  - name: rpc
    port: 6123
  - name: blob-server
    port: 6124
  - name: webui
    port: 8081
    nodePort: 30081  
  selector:
    app: flink
    component: jobmanager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager
  namespace: kitchen-sre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      component: jobmanager
  template:
    metadata:
      labels:
        app: flink
        component: jobmanager
    spec:
      containers:
      - name: jobmanager
        image: si3mshady/aiops:flink-v4    # The one built from Dockerfile.flink
        args: ["jobmanager"]
        ports:
        - containerPort: 6123
        - containerPort: 8081
        env:
        - name: JOB_MANAGER_RPC_ADDRESS
          value: "flink-jobmanager"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
  namespace: kitchen-sre
spec:
  replicas: 2 # Initial scale
  selector:
    matchLabels:
      app: flink
      component: taskmanager
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      containers:
      - name: taskmanager
        image: si3mshady/aiops:flink-v4   # Same image
        args: ["taskmanager"]
        env:
        - name: JOB_MANAGER_RPC_ADDRESS
          value: "flink-jobmanager"
