apiVersion: v1
kind: Namespace
metadata:
  name: kitchen-sre
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc
  namespace: kitchen-sre
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redpanda-pvc
  namespace: kitchen-sre
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
