kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080 # This matches Traefik's NodePort
    hostPort: 8080       # This is what you type in your browser
    protocol: TCP
