apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: virtual-svc
spec:
  hosts:
  - ghost.vision.ai
  gateways:
  - ai-sre-gateway-controller
  http:
  - route:
    - destination:
        host: dashboard
        port: 
          number: 8501
